name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: mig4/setup-bats@v1
    - uses: brokenpip3/setup-bats-libs@0.1.0
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
          target/
        key: ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}
          ${{ runner.os }}-
    - name: Build & lint
      run: |
        cargo build --verbose
        cargo fmt --check
        cargo clippy
    - name: Tests
      run: |
        cargo test
        bats test.bats
